<header>
            <nav>
              <ul id="menu">
                <li><a href="index.php">HOME</a></li>
                <li><a href="biography.php">BIOGRAPHY</a></li>
				<li><a href="mission.php">VISION</a></li>
                <li><a href="news.php">NEWS</a></li>
                <li><a href="program.php">PROGRAM</a></li>
				<li><a href="gallery.php">GALLERY</a></li>
                <li><a href="contacts.php">CONTACT US</a></li>
              </ul>
            </nav>
             <h1><a href="#" id="logo"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#000";></span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp </a></h1>
          </header>